version: "3"
services:
  app:
    network_mode: 'bridge'
    links:
      - kafka
      - spark
    environment:
      TWITTER_CONSUMER_KEY: '***'
      TWITTER_CONSUMER_SECRET: '***'
      TWITTER_ACCESS_TOKEN: '***'
      TWITTER_ACCESS_TOKEN_SECRET: '***'
  web:
    image: nginx:latest
    links:
      - kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
  spark:
    image: jupyter/pyspark-notebook
    links:
     - kafka
    expose:
      - "8888:8888"